name: Keep Backend Warm

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend service
        run: |
          curl -I -X GET https://leetcode-together-backend.onrender.com
          echo "Pinged backend at $(date)"
      - name: Check status
        if: ${{ success() }}
        run: echo "Backend is alive!"
