name: Auto Add & Remove Contests

on:
  schedule:
    - cron: '5 4 * * 0'   # Sundays 9:35 AM IST
    - cron: '5 16 * * 6'  # Saturdays 9:35 PM IST
  workflow_dispatch:

jobs:
  auto-contest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Run contest auto-add
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          cd backend
          node scripts/autoAddContest.js
