name: Auto Fetch LCCN Contest

on:
  schedule:
    # Saturday 10:30 PM IST → Saturday 17:00 UTC
    - cron: '0 17 * * 6'
    # Sunday 10:25 AM IST → Sunday 4:55 UTC
    - cron: '55 4 * * 0'
  workflow_dispatch:

jobs:
  fetch-lccn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd backend
          npm ci

      - name: Run autoFetchLccnContest script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
           cd backend
           node scripts/autoFetchLccnContest.js
